---
- hosts: linux
  become: yes
  tasks:
          - name: Latest apache version installed
            dnf:
                    name: httpd
                    state: latest
          - name: Latest mariadb install
            dnf:
                    name: mariadb-server
                    state: latest
                                            
          - name: Apache enabled and running
            service:
                    name: httpd mariadb
                    enabled: true
                    state: started


