---
- hosts: 192.168.21.3
  gather_facts: false
  vars:
    ssh_key: '/root/.ssh/id_rsa.pub'
  tasks:
    - name: copy ssh key
      authorized_key:
        key: "{{ lookup('file', ssh_key) }}"
        user: root
